// Concatenates the migrations and the seed into supabase/setup.sql, a single file you can
// paste into the Supabase SQL editor. (With the Supabase CLI, `supabase db push` works too.)
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = join(import.meta.dirname, '..', 'supabase');
const migrations = readdirSync(join(dir, 'migrations'))
  .filter((f) => f.endsWith('.sql'))
  .sort();

const parts = [
  '-- ArkStore setup: paste into Supabase > SQL Editor and run. Safe to run again.',
  '-- Generated by `npm run db:bundle` from supabase/migrations/* and supabase/seed.sql.',
  ...migrations.map((f) => `\n-- ===== migrations/${f} =====\n${readFileSync(join(dir, 'migrations', f), 'utf8')}`),
  `\n-- ===== seed.sql =====\n${readFileSync(join(dir, 'seed.sql'), 'utf8')}`,
];

writeFileSync(join(dir, 'setup.sql'), parts.join('\n'));
console.log(`Wrote supabase/setup.sql (${migrations.length} migrations + seed)`);
